USE master
GO

DROP DATABASE IF EXISTS BBM_ASPACE
GO

CREATE DATABASE BBM_ASPACE
	ON
		PRIMARY
			( NAME = BBM_ASPACE_PRINCIPAL,
			FILENAME = 'C:\DATABASE_BBMASPACE\BBM_ASPACE.mdf',
			SIZE = 10MB,
			MAXSIZE = 50,
			FILEGROWTH = 5% ),
			( NAME = BBM_ASPACE_SECONDARY,
			FILENAME = 'C:\DATABASE_BBMASPACE\BBM_ASPACE_SECONDARY.ndf',
			SIZE = 10MB,
			MAXSIZE = 50,
			FILEGROWTH = 5% )
		LOG ON
			( NAME = BBM_ASPACE_log,
			FILENAME = 'C:\DATABASE_BBMASPACE\BBM_ASPACE.ldf',
			SIZE = 10MB,
			MAXSIZE = 50,
			FILEGROWTH = 5% ) ;
GO



