-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2021-01-23 19:49:44 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012


USE BBM_ASPACE
GO


CREATE TABLE BBM_Actividades 
    (
     ACT_ID CHAR (10) , 
     Hora_Inicio DATETIME , 
     Hora_Fin DATETIME , 
     Emplazamiento VARCHAR (255) , 
     Descripcion VARCHAR (255) , 
     BBM_Actividades_ID INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL 
    )
GO

ALTER TABLE BBM_Actividades ADD CONSTRAINT BBM_Actividades_PK PRIMARY KEY CLUSTERED (BBM_Actividades_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Asistente_Social 
    (
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Asistente_Social ADD CONSTRAINT BBM_Asistente_Social_PK PRIMARY KEY CLUSTERED (BBM_Especialista_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Auxiliar 
    (
     BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     AUX_ID CHAR (6) NOT NULL 
    )
GO

ALTER TABLE BBM_Auxiliar ADD CONSTRAINT BBM_Auxiliar_PK PRIMARY KEY CLUSTERED (BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Cocina 
    (
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Cocina ADD CONSTRAINT BBM_Cocina_PK PRIMARY KEY CLUSTERED (BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Comida_Paciente 
    (
     BBM_Comidas_ID_Menu CHAR (9) NOT NULL , 
     BBM_Expediente_ID_Expediente VARCHAR (10) NOT NULL , 
     Plato_1 VARCHAR (30) , 
     Plato_2 VARCHAR (30) , 
     Plato_3 VARCHAR (30) , 
     Contraindicaciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Comida_Paciente ADD CONSTRAINT BBM_Comida_Paciente_PK PRIMARY KEY CLUSTERED (BBM_Comidas_ID_Menu, BBM_Expediente_ID_Expediente)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Comidas 
    (
     ID_Menu CHAR (9) NOT NULL , 
     Plato_1 VARCHAR (255) , 
     Plato_2 VARCHAR (255) , 
     Plato_3 VARCHAR (255) , 
     BBM_Otros_Departamentos_OD_ID CHAR (5) NOT NULL 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Día de la semana' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Comidas' , 'COLUMN' , 'ID_Menu' 
GO

ALTER TABLE BBM_Comidas ADD CONSTRAINT BBM_Comidas_PK PRIMARY KEY CLUSTERED (ID_Menu)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Contacto_Paciente 
    (
     BBM_Tutor_Tutor_ID VARCHAR (10) NOT NULL , 
     BBM_Usuario_Usuario_ID VARCHAR (10) NOT NULL , 
     Contacto INTEGER , 
     Email VARCHAR (255) , 
     Direciion VARCHAR (255) , 
     Otros_Detalles VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Contacto_Paciente ADD CONSTRAINT BBM_Contacto_Paciente_PK PRIMARY KEY CLUSTERED (BBM_Tutor_Tutor_ID, BBM_Usuario_Usuario_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Direccion 
    (
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Direccion ADD CONSTRAINT BBM_Direccion_PK PRIMARY KEY CLUSTERED (BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Empleado 
    (
     BBM_Empleado_ID INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     Empleado_ID CHAR (6) NOT NULL , 
     Nombre_1 VARCHAR (20) , 
     Nombre_2 VARCHAR (20) , 
     Apeliido_1 VARCHAR (20) , 
     Apeliido_2 VARCHAR (20) , 
     DNI VARCHAR (9) , 
     Telefono INTEGER , 
     Email VARCHAR (255) 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Iniciales + 3 ultimos digitos DNI' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Empleado' , 'COLUMN' , 'Empleado_ID' 
GO

ALTER TABLE BBM_Empleado ADD CONSTRAINT BBM_Empleado_PK PRIMARY KEY CLUSTERED (BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Enfermedad_Diagnosticada 
    (
     Nombre_Enfermedad VARCHAR (50) NOT NULL , 
     Nombre_Comun_Enfermedad VARCHAR (50) NOT NULL , 
     Descripcion VARCHAR (255) , 
     Sintomas VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Enfermedad_Diagnosticada ADD CONSTRAINT BBM_Enfermedad_Diagnosticada_PK PRIMARY KEY CLUSTERED (Nombre_Enfermedad)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Enfermera 
    (
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR 
    )
GO

ALTER TABLE BBM_Enfermera ADD CONSTRAINT BBM_Enfermera_PK PRIMARY KEY CLUSTERED (BBM_Especialista_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Equipamiento 
    (
     ID_Equipamiento CHAR (10) NOT NULL , 
     Codigo_EAN INTEGER , 
     Descripcion VARCHAR (255) , 
     Ocupado BIT NOT NULL 
    )
GO

ALTER TABLE BBM_Equipamiento ADD CONSTRAINT BBM_Equipamiento_PK PRIMARY KEY CLUSTERED (ID_Equipamiento)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Espacio 
    (
     ID_Espacio CHAR (10) NOT NULL , 
     Funcion VARCHAR (255) 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'En  función de si es un aula, una hbitación, una sala o despacho será:

AUL
HAB
	+  FUNCIÓN + NUMERO
SAL
DES

EJEMPLO:

AULTRAT010' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Espacio' , 'COLUMN' , 'ID_Espacio' 
GO

ALTER TABLE BBM_Espacio ADD CONSTRAINT BBM_Espacio_PK PRIMARY KEY CLUSTERED (ID_Espacio)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Especialista 
    (
     BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     ESPEC_ID CHAR (8) NOT NULL 
    )
GO

ALTER TABLE BBM_Especialista ADD CONSTRAINT BBM_Especialista_PK PRIMARY KEY CLUSTERED (BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Estimulacion_Electrica 
    (
     BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     Descripcion VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Estimulacion_Electrica ADD CONSTRAINT BBM_Estimulacion_Electrica_PK PRIMARY KEY CLUSTERED (BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Expediente 
    (
     ID_Expediente VARCHAR (10) NOT NULL , 
     BBM_Enfermedad_Diagnosticada_Nombre_Enfermedad VARCHAR (50) NOT NULL , 
     BBM_Usuario_Usuario_ID VARCHAR (10) NOT NULL , 
     BBM_Sesion_Sesion_ID CHAR (14) NOT NULL , 
     BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Compuesto por EXP + Apellido + Apellido + Nombre Usuario + Numeracion
Ejemplo: EXPBBM0001' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Expediente' , 'COLUMN' , 'ID_Expediente' 
GO

ALTER TABLE BBM_Expediente ADD CONSTRAINT BBM_Expediente_PK PRIMARY KEY CLUSTERED (ID_Expediente)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Factura 
    (
     Num_Factura INTEGER NOT NULL , 
     Fecha_expedicion DATE , 
     Cantidad NUMERIC (5,2) , 
     IVA NUMERIC (1,1) , 
     Total NUMERIC (5,2) , 
     BBM_Tutor_Tutor_ID VARCHAR (10) NOT NULL , 
     BBM_Horario_ID_Horario CHAR (8) NOT NULL , 
     BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL 
    )
GO

ALTER TABLE BBM_Factura ADD CONSTRAINT BBM_Factura_PK PRIMARY KEY CLUSTERED (Num_Factura)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Fisioterapeutas 
    (
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Fisioterapeutas ADD CONSTRAINT BBM_Fisioterapeutas_PK PRIMARY KEY CLUSTERED (BBM_Especialista_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Fisioterapia 
    (
     BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     FIS_ID CHAR (9) NOT NULL , 
     Descripcion VARCHAR (255) , 
     ESPEC_ID CHAR 
    )
GO

ALTER TABLE BBM_Fisioterapia ADD CONSTRAINT BBM_Fisioterapia_PK PRIMARY KEY CLUSTERED (BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Horario 
    (
     ID_Horario CHAR (8) NOT NULL , 
     Diurno BIT , 
     Nocturno BIT , 
     Mañana BIT , 
     Tarde BIT 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Para distinguir de Nocturno, diurno o media jornada' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Horario' , 'COLUMN' , 'ID_Horario' 
GO

ALTER TABLE BBM_Horario ADD CONSTRAINT BBM_Horario_PK PRIMARY KEY CLUSTERED (ID_Horario)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Horario_Diurno 
    (
     "07:00-08:00" VARCHAR (255) , 
     "08:00-09:00" VARCHAR (255) , 
     "09:00-10:00" VARCHAR (255) , 
     "10:00-11:00" VARCHAR (255) , 
     "11:00-12:00" VARCHAR (255) , 
     "12:00-13:00" VARCHAR (255) , 
     "13:00-14:00" VARCHAR (255) , 
     "14:00-15:00" VARCHAR (255) , 
     "15:00-16:00" VARCHAR (255) , 
     "16:00-17:00" VARCHAR (255) , 
     "17:00-18:00" VARCHAR (255) , 
     "18:00-19:00" VARCHAR (255) , 
     BBM_Horario_ID_Horario CHAR (8) NOT NULL 
    )
GO

CREATE TABLE BBM_Horario_Fabricado 
    (
     "00:00-01:00" VARCHAR (255) , 
     "01:00-02:00" VARCHAR (255) , 
     "02:00-03:00" VARCHAR (255) , 
     "03:00-04:00" VARCHAR (255) , 
     "04:00-05:00" VARCHAR (255) , 
     "05:00-06:00" VARCHAR (255) , 
     "06:00-07:00" VARCHAR (255) , 
     "07:00-08:00" VARCHAR (255) , 
     "08:00-09:00" VARCHAR (255) , 
     "09:00-10:00" VARCHAR (255) , 
     "10:00-11:00" VARCHAR (255) , 
     "11:00-12:00" VARCHAR (255) , 
     "12:00-13:00" VARCHAR (255) , 
     "13:00-14:00" VARCHAR (255) , 
     "14:00-15:00" VARCHAR (255) , 
     "15:00-16:00" VARCHAR (255) , 
     "16:00-17:00" VARCHAR (255) , 
     "17:00-18:00" VARCHAR (255) , 
     "18:00-19:00" VARCHAR (255) , 
     "19:00-20:00" VARCHAR (255) , 
     "20:00-21:00" VARCHAR (255) , 
     "22:00-21:00" VARCHAR (255) , 
     "22:00-23:00" VARCHAR (255) , 
     "23:00-00:00" VARCHAR (255) , 
     BBM_Horario_ID_Horario CHAR (8) NOT NULL 
    )
GO

CREATE TABLE BBM_Horario_Nocturno 
    (
     Numero_Camas INTEGER , 
     BBM_Horario_ID_Horario CHAR (8) NOT NULL 
    )
GO

CREATE TABLE BBM_IT 
    (
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_IT ADD CONSTRAINT BBM_IT_PK PRIMARY KEY CLUSTERED (BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Logopeda 
    (
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR 
    )
GO

ALTER TABLE BBM_Logopeda ADD CONSTRAINT BBM_Logopeda_PK PRIMARY KEY CLUSTERED (BBM_Especialista_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Mantenimiento 
    (
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Mantenimiento ADD CONSTRAINT BBM_Mantenimiento_PK PRIMARY KEY CLUSTERED (BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Medicacion 
    (
     ID_Medicacion CHAR (12) NOT NULL , 
     Nombre_Medicamento VARCHAR (25) NOT NULL , 
     Codigo_EAN INTEGER NOT NULL , 
     Fabricante VARCHAR (50) , 
     Posologia VARCHAR (255) , 
     Descripcion VARCHAR (255) , 
     Observaciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Medicacion ADD CONSTRAINT BBM_Medicacion_PK PRIMARY KEY CLUSTERED (ID_Medicacion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Medicacion_Paciente 
    (
     BBM_Medicacion_ID_Medicacion CHAR (12) NOT NULL , 
     BBM_Expediente_ID_Expediente VARCHAR (10) NOT NULL , 
     Toma_1 DATETIME , 
     Toma_2 DATETIME , 
     Toma_3 DATETIME , 
     Toma_4 DATETIME , 
     Toma_5 DATETIME 
    )
GO

ALTER TABLE BBM_Medicacion_Paciente ADD CONSTRAINT BBM_Medicacion_Paciente_PK PRIMARY KEY CLUSTERED (BBM_Medicacion_ID_Medicacion, BBM_Expediente_ID_Expediente)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Metodo_Doman 
    (
     BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     Descripcion VARCHAR (255) NOT NULL 
    )
GO

ALTER TABLE BBM_Metodo_Doman ADD CONSTRAINT BBM_Metodo_Doman_PK PRIMARY KEY CLUSTERED (BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Otras_Terapias 
    (
     BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     OTT_ID CHAR (9) NOT NULL , 
     BBM_Tratamientos_BBM_Tratamientos_ID2 INTEGER NOT NULL 
    )
GO

ALTER TABLE BBM_Otras_Terapias ADD CONSTRAINT BBM_Otras_Terapias_PK PRIMARY KEY CLUSTERED (BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Otros_Departamentos 
    (
     BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     OD_ID CHAR (5) NOT NULL 
    )
GO

ALTER TABLE BBM_Otros_Departamentos ADD CONSTRAINT BBM_Otros_Departamentos_PK PRIMARY KEY CLUSTERED (BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE BBM_Otros_Departamentos ADD CONSTRAINT BBM_Otros_Departamentos_OD_ID_UN UNIQUE NONCLUSTERED (OD_ID)
GO

CREATE TABLE BBM_Oxigencion_Hiperbarica 
    (
     BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     Descripcion VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Oxigencion_Hiperbarica ADD CONSTRAINT BBM_Oxigencion_Hiperbarica_PK PRIMARY KEY CLUSTERED (BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Psicologo 
    (
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Psicologo ADD CONSTRAINT BBM_Psicologo_PK PRIMARY KEY CLUSTERED (BBM_Especialista_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Sesion 
    (
     Sesion_ID CHAR (14) NOT NULL , 
     Fecha_y_Hora_de_inicio DATETIME , 
     Fecha_y_Hora_de_fin DATETIME , 
     BBM_Horario_ID_Horario CHAR (8) NOT NULL , 
     BBM_Espacio_ID_Espacio CHAR (10) NOT NULL , 
     BBM_Equipamiento_ID_Equipamiento CHAR (10) NOT NULL , 
     BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     BBM_Actividades_BBM_Actividades_ID INTEGER NOT NULL 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Sesion + ddmmaa + orden 

ejemplo  SES07122020010' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Sesion' , 'COLUMN' , 'Sesion_ID' 
GO

ALTER TABLE BBM_Sesion ADD CONSTRAINT BBM_Sesion_PK PRIMARY KEY CLUSTERED (Sesion_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Terapeuta_Ocupacional 
    (
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Terapeuta_Ocupacional ADD CONSTRAINT BBM_Terapeuta_Ocupacional_PK PRIMARY KEY CLUSTERED (BBM_Especialista_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Terapia_Logopeda 
    (
     BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     TL_ID CHAR (9) NOT NULL , 
     Descripcion VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Terapia_Logopeda ADD CONSTRAINT BBM_Terapia_Logopeda_PK PRIMARY KEY CLUSTERED (BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Terapia_Ocupacional 
    (
     BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     TO_ID CHAR (9) NOT NULL , 
     Descripcion VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Terapia_Ocupacional ADD CONSTRAINT BBM_Terapia_Ocupacional_PK PRIMARY KEY CLUSTERED (BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Terapia_Recreativa 
    (
     BBM_Tratamientos_BBM_Tratamientos_ID INTEGER NOT NULL , 
     TR_ID CHAR (9) NOT NULL , 
     Descripcion VARCHAR (255) , 
     AUX_ID CHAR NOT NULL 
    )
GO

ALTER TABLE BBM_Terapia_Recreativa ADD CONSTRAINT BBM_Terapia_Recreativa_PK PRIMARY KEY CLUSTERED (BBM_Tratamientos_BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Titulado 
    (
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Titulado ADD CONSTRAINT BBM_Titulado_PK PRIMARY KEY CLUSTERED (BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Tratamientos 
    (
     BBM_Tratamientos_ID INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     Tratamiento_ID CHAR (4) NOT NULL , 
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL 
    )
GO

ALTER TABLE BBM_Tratamientos ADD CONSTRAINT BBM_Tratamientos_PK PRIMARY KEY CLUSTERED (BBM_Tratamientos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Tutor 
    (
     Tutor_ID VARCHAR (10) NOT NULL , 
     Nombre_1 VARCHAR (20) , 
     Nombre_2 VARCHAR (20) , 
     Apellido_1 VARCHAR (20) , 
     Apellido_2 VARCHAR (20) , 
     DNI VARCHAR (9) NOT NULL , 
     Otros_Detalles VARCHAR (255) 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Codigo compuesto por TUT + ID del Usuario (Apellido + Apellido + Nombre + Numero)
ejemplo -> TUTBBM0001' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Tutor' , 'COLUMN' , 'Tutor_ID' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Para decir cosas que pueden ir adicionales' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Tutor' , 'COLUMN' , 'Otros_Detalles' 
GO

ALTER TABLE BBM_Tutor ADD CONSTRAINT BBM_Tutor_PK PRIMARY KEY CLUSTERED (Tutor_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Usuario 
    (
     Usuario_ID VARCHAR (10) NOT NULL , 
     Nombre_1 VARCHAR (20) , 
     Nombre_2 VARCHAR (20) , 
     Apellido_1 VARCHAR (20) , 
     Apellido_2 VARCHAR (20) , 
     DNI VARCHAR (9) NOT NULL , 
     Otros_Detalles VARCHAR (255) 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Codigo compuesto por PACX + ID del Usuario (Apellido + Apellido + Nombre + Numero)
ejemplo -> PACBBM0001' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Usuario' , 'COLUMN' , 'Usuario_ID' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Por si hay algo que añadir a mayores, como puede ser un segundo contacto' , 'USER' , 'dbo' , 'TABLE' , 'BBM_Usuario' , 'COLUMN' , 'Otros_Detalles' 
GO

ALTER TABLE BBM_Usuario ADD CONSTRAINT BBM_Usuario_PK PRIMARY KEY CLUSTERED (Usuario_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE BBM_Voluntario 
    (
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID INTEGER NOT NULL , 
     Descripcion_funciones VARCHAR (255) 
    )
GO

ALTER TABLE BBM_Voluntario ADD CONSTRAINT BBM_Voluntario_PK PRIMARY KEY CLUSTERED (BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE BBM_Actividades 
    ADD CONSTRAINT BBM_Actividades_BBM_Auxiliar_FK FOREIGN KEY 
    ( 
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Auxiliar 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Asistente_Social 
    ADD CONSTRAINT BBM_Asistente_Social_BBM_Especialista_FK FOREIGN KEY 
    ( 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Especialista 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Auxiliar 
    ADD CONSTRAINT BBM_Auxiliar_BBM_Empleado_FK FOREIGN KEY 
    ( 
     BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Empleado 
    ( 
     BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Cocina 
    ADD CONSTRAINT BBM_Cocina_BBM_Otros_Departamentos_FK FOREIGN KEY 
    ( 
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Otros_Departamentos 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Comida_Paciente 
    ADD CONSTRAINT BBM_Comida_Paciente_BBM_Comidas_FK FOREIGN KEY 
    ( 
     BBM_Comidas_ID_Menu
    ) 
    REFERENCES BBM_Comidas 
    ( 
     ID_Menu 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Comida_Paciente 
    ADD CONSTRAINT BBM_Comida_Paciente_BBM_Expediente_FK FOREIGN KEY 
    ( 
     BBM_Expediente_ID_Expediente
    ) 
    REFERENCES BBM_Expediente 
    ( 
     ID_Expediente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Comidas 
    ADD CONSTRAINT BBM_Comidas_BBM_Otros_Departamentos_FK FOREIGN KEY 
    ( 
     BBM_Otros_Departamentos_OD_ID
    ) 
    REFERENCES BBM_Otros_Departamentos 
    ( 
     OD_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Contacto_Paciente 
    ADD CONSTRAINT BBM_Contacto_Paciente_BBM_Tutor_FK FOREIGN KEY 
    ( 
     BBM_Tutor_Tutor_ID
    ) 
    REFERENCES BBM_Tutor 
    ( 
     Tutor_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Contacto_Paciente 
    ADD CONSTRAINT BBM_Contacto_Paciente_BBM_Usuario_FK FOREIGN KEY 
    ( 
     BBM_Usuario_Usuario_ID
    ) 
    REFERENCES BBM_Usuario 
    ( 
     Usuario_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Direccion 
    ADD CONSTRAINT BBM_Direccion_BBM_Otros_Departamentos_FK FOREIGN KEY 
    ( 
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Otros_Departamentos 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Enfermera 
    ADD CONSTRAINT BBM_Enfermera_BBM_Especialista_FK FOREIGN KEY 
    ( 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Especialista 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Especialista 
    ADD CONSTRAINT BBM_Especialista_BBM_Empleado_FK FOREIGN KEY 
    ( 
     BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Empleado 
    ( 
     BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Estimulacion_Electrica 
    ADD CONSTRAINT BBM_Estimulacion_Electrica_BBM_Otras_Terapias_FK FOREIGN KEY 
    ( 
     BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Otras_Terapias 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Expediente 
    ADD CONSTRAINT BBM_Expediente_BBM_Enfermedad_Diagnosticada_FK FOREIGN KEY 
    ( 
     BBM_Enfermedad_Diagnosticada_Nombre_Enfermedad
    ) 
    REFERENCES BBM_Enfermedad_Diagnosticada 
    ( 
     Nombre_Enfermedad 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Expediente 
    ADD CONSTRAINT BBM_Expediente_BBM_Sesion_FK FOREIGN KEY 
    ( 
     BBM_Sesion_Sesion_ID
    ) 
    REFERENCES BBM_Sesion 
    ( 
     Sesion_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Expediente 
    ADD CONSTRAINT BBM_Expediente_BBM_Tratamientos_FK FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Expediente 
    ADD CONSTRAINT BBM_Expediente_BBM_Usuario_FK FOREIGN KEY 
    ( 
     BBM_Usuario_Usuario_ID
    ) 
    REFERENCES BBM_Usuario 
    ( 
     Usuario_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Factura 
    ADD CONSTRAINT BBM_Factura_BBM_Horario_FK FOREIGN KEY 
    ( 
     BBM_Horario_ID_Horario
    ) 
    REFERENCES BBM_Horario 
    ( 
     ID_Horario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Factura 
    ADD CONSTRAINT BBM_Factura_BBM_Tratamientos_FK FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Factura 
    ADD CONSTRAINT BBM_Factura_BBM_Tutor_FK FOREIGN KEY 
    ( 
     BBM_Tutor_Tutor_ID
    ) 
    REFERENCES BBM_Tutor 
    ( 
     Tutor_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Fisioterapeutas 
    ADD CONSTRAINT BBM_Fisioterapeutas_BBM_Especialista_FK FOREIGN KEY 
    ( 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Especialista 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Fisioterapia 
    ADD CONSTRAINT BBM_Fisioterapia_BBM_Tratamientos_FK FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Horario_Diurno 
    ADD CONSTRAINT BBM_Horario_Diurno_BBM_Horario_FK FOREIGN KEY 
    ( 
     BBM_Horario_ID_Horario
    ) 
    REFERENCES BBM_Horario 
    ( 
     ID_Horario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Horario_Fabricado 
    ADD CONSTRAINT BBM_Horario_Fabricado_BBM_Horario_FK FOREIGN KEY 
    ( 
     BBM_Horario_ID_Horario
    ) 
    REFERENCES BBM_Horario 
    ( 
     ID_Horario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Horario_Nocturno 
    ADD CONSTRAINT BBM_Horario_Nocturno_BBM_Horario_FK FOREIGN KEY 
    ( 
     BBM_Horario_ID_Horario
    ) 
    REFERENCES BBM_Horario 
    ( 
     ID_Horario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_IT 
    ADD CONSTRAINT BBM_IT_BBM_Otros_Departamentos_FK FOREIGN KEY 
    ( 
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Otros_Departamentos 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Logopeda 
    ADD CONSTRAINT BBM_Logopeda_BBM_Especialista_FK FOREIGN KEY 
    ( 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Especialista 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Mantenimiento 
    ADD CONSTRAINT BBM_Mantenimiento_BBM_Otros_Departamentos_FK FOREIGN KEY 
    ( 
     BBM_Otros_Departamentos_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Otros_Departamentos 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Medicacion_Paciente 
    ADD CONSTRAINT BBM_Medicacion_Paciente_BBM_Expediente_FK FOREIGN KEY 
    ( 
     BBM_Expediente_ID_Expediente
    ) 
    REFERENCES BBM_Expediente 
    ( 
     ID_Expediente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Medicacion_Paciente 
    ADD CONSTRAINT BBM_Medicacion_Paciente_BBM_Medicacion_FK FOREIGN KEY 
    ( 
     BBM_Medicacion_ID_Medicacion
    ) 
    REFERENCES BBM_Medicacion 
    ( 
     ID_Medicacion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Metodo_Doman 
    ADD CONSTRAINT BBM_Metodo_Doman_BBM_Otras_Terapias_FK FOREIGN KEY 
    ( 
     BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Otras_Terapias 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Otras_Terapias 
    ADD CONSTRAINT BBM_Otras_Terapias_BBM_Tratamientos_FK FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Otras_Terapias 
    ADD CONSTRAINT BBM_Otras_Terapias_BBM_Tratamientos_FKv2 FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID2
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Otros_Departamentos 
    ADD CONSTRAINT BBM_Otros_Departamentos_BBM_Empleado_FK FOREIGN KEY 
    ( 
     BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Empleado 
    ( 
     BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Oxigencion_Hiperbarica 
    ADD CONSTRAINT BBM_Oxigencion_Hiperbarica_BBM_Otras_Terapias_FK FOREIGN KEY 
    ( 
     BBM_Otras_Terapias_BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Otras_Terapias 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Psicologo 
    ADD CONSTRAINT BBM_Psicologo_BBM_Especialista_FK FOREIGN KEY 
    ( 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Especialista 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Sesion 
    ADD CONSTRAINT BBM_Sesion_BBM_Actividades_FK FOREIGN KEY 
    ( 
     BBM_Actividades_BBM_Actividades_ID
    ) 
    REFERENCES BBM_Actividades 
    ( 
     BBM_Actividades_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Sesion 
    ADD CONSTRAINT BBM_Sesion_BBM_Empleado_FK FOREIGN KEY 
    ( 
     BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Empleado 
    ( 
     BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Sesion 
    ADD CONSTRAINT BBM_Sesion_BBM_Equipamiento_FK FOREIGN KEY 
    ( 
     BBM_Equipamiento_ID_Equipamiento
    ) 
    REFERENCES BBM_Equipamiento 
    ( 
     ID_Equipamiento 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Sesion 
    ADD CONSTRAINT BBM_Sesion_BBM_Espacio_FK FOREIGN KEY 
    ( 
     BBM_Espacio_ID_Espacio
    ) 
    REFERENCES BBM_Espacio 
    ( 
     ID_Espacio 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Sesion 
    ADD CONSTRAINT BBM_Sesion_BBM_Horario_FK FOREIGN KEY 
    ( 
     BBM_Horario_ID_Horario
    ) 
    REFERENCES BBM_Horario 
    ( 
     ID_Horario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Terapeuta_Ocupacional 
    ADD CONSTRAINT BBM_Terapeuta_Ocupacional_BBM_Especialista_FK FOREIGN KEY 
    ( 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Especialista 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Terapia_Logopeda 
    ADD CONSTRAINT BBM_Terapia_Logopeda_BBM_Tratamientos_FK FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Terapia_Ocupacional 
    ADD CONSTRAINT BBM_Terapia_Ocupacional_BBM_Tratamientos_FK FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Terapia_Recreativa 
    ADD CONSTRAINT BBM_Terapia_Recreativa_BBM_Tratamientos_FK FOREIGN KEY 
    ( 
     BBM_Tratamientos_BBM_Tratamientos_ID
    ) 
    REFERENCES BBM_Tratamientos 
    ( 
     BBM_Tratamientos_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Titulado 
    ADD CONSTRAINT BBM_Titulado_BBM_Auxiliar_FK FOREIGN KEY 
    ( 
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Auxiliar 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Tratamientos 
    ADD CONSTRAINT BBM_Tratamientos_BBM_Auxiliar_FK FOREIGN KEY 
    ( 
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Auxiliar 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Tratamientos 
    ADD CONSTRAINT BBM_Tratamientos_BBM_Especialista_FK FOREIGN KEY 
    ( 
     BBM_Especialista_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Especialista 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BBM_Voluntario 
    ADD CONSTRAINT BBM_Voluntario_BBM_Auxiliar_FK FOREIGN KEY 
    ( 
     BBM_Auxiliar_BBM_Empleado_BBM_Empleado_ID
    ) 
    REFERENCES BBM_Auxiliar 
    ( 
     BBM_Empleado_BBM_Empleado_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            43
-- CREATE INDEX                             0
-- ALTER TABLE                             90
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
