transact

BASES DE DATOS CONTENIDAS. TIENEN UN LINK ENTRE LA BASES DE DATOS Y LOS CONTENIDOS. SE SUPONE QUE EN ESTA BASE LOS LOGIN ESTÁN INTEGRADOS EN LA BASE, LO QUE LA CONVIERTE EN TOTALMENTE INDEPENDIENTE DEL SERVIDOR.

CREAMOS BASE DE DATOS
CREAMOS USUARIOS
VEMOS LO QUE SE PUEDE HACER

LO HACEMOS CONTENIDA_BBM Y EL USUARIO ES BBM

USE MASTER
-- 1 ACTIVA OPCIONES AVANZADAS
EXEC SP_CONFIGURE 'show advanced options', 1 --> Para cambiar las asignaciones de la instancia para activar las opciones avanzadas del sistema. 1 QUIERE DECIR QUE SE ACTIVA
GO

-- HAY TRES TIPOS DE PROCEDIMINETOS ALMACENADOS (LOS QUE EMPIEZAN POR SP SON LOS QUE CREAN MICROSOFT, Y SON LOS PROCEDIMINETOS ALMACENADOS DEL SISTEMA). LOS QUE CREAN LA COMUNIDAD (XP_) -> MICROSOFT NO SE HACE RESPONDABLE DE ESTOS

RECONFIGURE -- PUEDO REINICIAR LA INSTANCIA PARA QUE EMPIECE A FUNCIONAR EL PROCEDIMIENTO ALMACENADO DEL SISTEMA
GO
--> EL MENSAJE QUE PONE: Configuration option 'show advanced options' changed from 0 to 1. Run the RECONFIGURE statement to install.

--ACTIVAMOS LA CARASTERÍSTICA DE LA BASE DE DATOS CONTENIDA EN PARTICULAR
EXEC sp_configure 'contained database authentication', 1
GO
-- Actualizamos de nuevo
RECONFIGURE
GO
--> EL MENSAJE: Configuration option 'contained database authentication' changed from 0 to 1. Run the RECONFIGURE statement to install.
--hasta aquí preparamos el entornopara lo que vamos a ejecutar

DROP DATABASE IF EXISTS CONTENIDA_BBM
GO


CREATE DATABASE CONTENIDA_BBM
CONTAINMENT=PARTIAL
GO

-- La activamos
USE CONTENIDA_BBM
GO

-- Creamos un usuario que son mis iniciales BBM. Asocio el esquema dbo
DROP USER IF EXISTS BBM
GO

CREATE USER BBM
	WITH PASSWORD='Abcd1234.',
	DEFAULT_SCHEMA=[dbo]
GO


-- AÑADIMOS EL USUARIO BBM AL ROL db_owner. RECORDAR QUE HAY ROLES DE SERVIDOR, ROLES DE BASES DE DATOS Y ROLES DE APLICACIÓN. LOS ROLES DE BASES DE DATOS SON FIJOS O CREADOS POR NOSOTROS. EL MÁS IMPORTANTE EL dbo_owner. VOY A AÑADIR BBM A ESE ROL. HAY DOS FORMAS:
EXEC sp_addrolemember 'db_owner', 'BBM' --> La versión deprecated
GO

ALTER ROLE db_owner --> FORMA NUEVA Y APROPIADA
ADD MEMBER BBM
GO
 --> RECORDAR QUE AL AGREGAR A UN USUARIO AL ROL, ÉSTE COGE LOS PERMISOS HEREDADOS DEL ROL

 --> PARA VER LOS ROLES ESTÁN EN LA BASE DE DATOS>SECURITY>DATABASE ROLES>...



 --> PROBAMOS CON UN REINICIO DEL SERVER
 --Intento conectarme BBM -> Abcd1234.
 --> Va a dar error DICIENDO QUE NO TENGO LOGIN. REALMENTE LO QUE NO TENGO CONCEDIDA ES LA POSIBILIDAD DE CONEXIÓN.

 --> NOS VAMOS AL USUARIO sa A DARLE PERMISO DE CONEXIÓN, Y VUELVE A FALLAR
 GRANT CONNECT TO BBM
 GO

 -- INTENTAMOS CONECTARNOS NUEVAMENTE Y VUELVE A FALLAR


 -- AL SER UNA BASE DE DATOS CONTENIDA TENDO QUE DARLE UNA OPCIÓN.
-- EN EL MOMENTO DE CONEXIÓN , ME VOY A OPCIONES DONDE LA CONEXIÓN>ADDITIONAL CONNECTION PARAMETERS Y LE METO DATABASE=CONTENIDA_BBM

-- PARA PROBAR, VAMOS A CAMBIAR DE SESIÓN PARA COMPROBAR QUE FUNCIONA. ESO SE HACE CLIC DE BOTÓN IZQUIERDO SOBRE LA SESIÓN Y LE DAMOS A NEW QUERY.
-- PARA COMPROBAR QUE BBM PUEDE HACER ALGO, CREAMOS UNA TABLA.
CREATE TABLE [dbo].[TablaContenida_BBM](
	[Codigo] [nchar](10) NULL,
	[Nombre] [nchar](10) NULL
) ON [PRIMARY]
GO








