
USE BBM_ASPACE
GO

/*scalar function (scalar UDF) para obtener rápidamente precios standar*/
DROP TABLE IF EXISTS trial.BBM_STANDARDPRICE
GO

CREATE TABLE trial.BBM_STANSARDPRICE
(
Identificador varchar (255),
Tipo varchar (255),
Precio int)
GO

INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('COMIDA','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('COMIDA','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('COMIDA','SIMPLE','5')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('HORARIO','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('HORARIO','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('HORARIO','SIMPLE','5')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('ACTIVIDAD','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('ACTIVIDAD','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('ACTIVIDAD','SIMPLE','5')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('SESION','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('SESION','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('SESION','SIMPLE','5')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('TERAPIA','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('TERAPIA','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('TERAPIA','SIMPLE','5')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('DOMAN','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('DOMAN','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('DOMAN','SIMPLE','5')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('MEDICACION','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('MEDICACION','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('MEDICACION','SIMPLE','5')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('TRATAMIENTOS','COMPLETA','15')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('TRATAMIENTOS','MEDIA','10')
INSERT INTO [trial].[BBM_STANSARDPRICE] VALUES('TRATAMIENTOS','SIMPLE','5')


SELECT * FROM trial.BBM_STANSARDPRICE

/*CHECK THE FUNCTION EXISTENCE*/
DROP FUNCTION IF EXISTS trial.BBM_GETPRICESIMPLE
DROP FUNCTION IF EXISTS trial.BBM_GETPRICEMEDIA
DROP FUNCTION IF EXISTS trial.BBM_GETPRICECOMPLETE

/*CREATE FUNCTION FOR STANDARD PRICE SIMPLE PLAN*/
CREATE FUNCTION trial.BBM_GETPRICESIMPLE
(
@GROSSPRICE INT,
@finalprice int
)
RETURNS int
AS
--returns the monthlybill
BEGIN
		SET @finalprice = (SELECT SUM (p.Precio)
		from trial.BBM_STANSARDPRICE p
		where p.Tipo = 'SIMPLE');
		SET @GROSSPRICE = @finalprice;
	RETURN @finalprice + (@GROSSPRICE * 0.21);
END;

/*CREATE FUNCTION FOR STANDARD PRICE MEDIA PLAN*/
CREATE FUNCTION trial.BBM_GETPRICEMEDIA
(
@GROSSPRICE INT,
@finalprice int
)
RETURNS int
AS
--returns the monthlybill
BEGIN
		SET @finalprice = (SELECT SUM (p.Precio)
		from trial.BBM_STANSARDPRICE p
		where p.Tipo = 'MEDIA');
		SET @GROSSPRICE = @finalprice;
	RETURN @finalprice + (@GROSSPRICE * 0.21);
END;

/*CREATE FUNCTION FOR STANDARD PRICE COMPLETA PLAN*/
CREATE FUNCTION trial.BBM_GETPRICECOMPLETE
(
@GROSSPRICE INT,
@finalprice int
)
RETURNS int
AS
--returns the monthlybill
BEGIN
		SET @finalprice = (SELECT SUM (p.Precio)
		from trial.BBM_STANSARDPRICE p
		where p.Tipo = 'COMPLETA');
		SET @GROSSPRICE = @finalprice;
	RETURN @finalprice + (@GROSSPRICE * 0.21);
END;

/*RESULTS*/
PRINT trial.BBM_GETPRICESIMPLE ('','')
PRINT trial.BBM_GETPRICEMEDIA ('','')
PRINT trial.BBM_GETPRICECOMPLETE ('','')

