USE BBM_ASPACE

/*CREAMOS TABLA PARA SUPUESTO, DONDE SE VA  A HACER ASIGNACIÓN DE PACIENTES DIARIOS POR PROFESIONAL Y AUXILIAR*/

/*TABLA PROS*/
DROP TABLE IF EXISTS trial.BBM_USERDATASSIGNEDPROS

CREATE TABLE trial.BBM_USERDATASSIGNEDPROS
(
	ROW# int identity (1,1),
	Usuario varchar (20) NOT NULL, 
	Nombre_Usuario varchar(10) NULL, 
	Pro_asignado Varchar(30) NULL, 
    Aux_asignado varchar(30)
)
GO


  /*INSERTAMOS VALORES A LA TABLA*/

INSERT INTO trial.BBM_USERDATASSIGNEDPROS VALUES 
   ('USER01','Pepe','PSICOLOGO','AUX01'),
   ('USER02','Paco','LOGOPEDA','AUX02'),
   ('USER03','Lola','ASISTENTE_SOCIAL','AUX03'),
   ('USER04','Diana','TERAPEUTA_OCUPACIONAL','AUX04'),
   ('USER05','Jose','FISIOTERAPEUTA','AUX05'),
   ('USER06','Luis','PSICOLOGO','AUX05'),
   ('USER07','Julia','LOGOPEDA','AUX04'),
   ('USER08','Cristina','ASISTENTE_SOCIAL','AUX03'),
   ('USER08','Toribio','TERAPEUTA_OCUPACIONAL','AUX02'),
   ('USER00','Brigida','FISIOTERAPEUTA','AUX01');
GO									 
--(10 rows affected)


SELECT * FROM trial.BBM_USERDATASSIGNEDPROS

/*POR UN BUG CON LOS PERMISOS TENGO QUE DUPLICAR LA TABLA EN VEZ DE SELECT * INTO*/
DROP TABLE IF EXISTS trial.BBM_USERDATASSIGNEDAUX

CREATE TABLE trial.BBM_USERDATASSIGNEDAUX
(
	ROW# int identity (1,1),
	Usuario varchar (20) NOT NULL, 
	Nombre_Usuario varchar(10) NULL, 
	Pro_asignado Varchar(30) NULL, 
    Aux_asignado varchar(30)
)
GO


  /*INSERTAMOS VALORES A LA TABLA*/

INSERT INTO trial.BBM_USERDATASSIGNEDAUX VALUES 
   ('USER01','Pepe','PSICOLOGO','AUX01'),
   ('USER02','Paco','LOGOPEDA','AUX02'),
   ('USER03','Lola','ASISTENTE_SOCIAL','AUX03'),
   ('USER04','Diana','TERAPEUTA_OCUPACIONAL','AUX04'),
   ('USER05','Jose','FISIOTERAPEUTA','AUX05'),
   ('USER06','Luis','PSICOLOGO','AUX05'),
   ('USER07','Julia','LOGOPEDA','AUX04'),
   ('USER08','Cristina','ASISTENTE_SOCIAL','AUX03'),
   ('USER08','Toribio','TERAPEUTA_OCUPACIONAL','AUX02'),
   ('USER00','Brigida','FISIOTERAPEUTA','AUX01');
GO									 
--(10 rows affected)


SELECT * FROM trial.BBM_USERDATASSIGNEDAUX





/*CREAMOS LOS PROS*/

CREATE USER PSICOLOGO WITHOUT LOGIN; 
CREATE USER LOGOPEDA WITHOUT LOGIN;
CREATE USER ASISTENTE_SOCIAL WITHOUT LOGIN;
CREATE USER TERAPEUTA_OCUPACIONAL WITHOUT LOGIN; 
CREATE USER FISIOTERAPEUTA WITHOUT LOGIN;


/*CREAMOS LOS AUXILIARES*/
CREATE USER AUX01 WITHOUT LOGIN; 
CREATE USER AUX02 WITHOUT LOGIN;
CREATE USER AUX03 WITHOUT LOGIN;
CREATE USER AUX04 WITHOUT LOGIN; 
CREATE USER AUX05 WITHOUT LOGIN;


/*CREAMOS EL ROL DE LOS PROS*/
CREATE ROLE BBM_PROFESIONALES

/*CREAMOS EL ROL DE LOS AUXILIARES*/
CREATE ROLE BBM_AUXILIARES


/*AÑADIMOS USUARIOS AL ROL DE LOS PROS*/
ALTER ROLE BBM_PROFESIONALES ADD MEMBER PSICOLOGO
ALTER ROLE BBM_PROFESIONALES ADD MEMBER LOGOPEDA 
ALTER ROLE BBM_PROFESIONALES ADD MEMBER ASISTENTE_SOCIAL
ALTER ROLE BBM_PROFESIONALES ADD MEMBER TERAPEUTA_OCUPACIONAL
ALTER ROLE BBM_PROFESIONALES ADD MEMBER FISIOTERAPEUTA


/*AÑADIMOS USUARIOS AL ROL DE LOS AUXILIARES*/
ALTER ROLE BBM_AUXILIARES ADD MEMBER AUX01
ALTER ROLE BBM_AUXILIARES ADD MEMBER AUX02
ALTER ROLE BBM_AUXILIARES ADD MEMBER AUX03
ALTER ROLE BBM_AUXILIARES ADD MEMBER AUX04
ALTER ROLE BBM_AUXILIARES ADD MEMBER AUX05




	-- =============================================
-- Create View template
-- =============================================
USE BBM_ASPACE
GO

DROP VIEW IF EXISTS trial.VIEWRLSPROS

CREATE VIEW trial.VIEWRLSPROS WITH SCHEMABINDING AS
SELECT        Usuario, Nombre_Usuario, Pro_asignado
FROM            trial.BBM_USERDATASSIGNEDPROS
go

PRINT USER
SELECT * FROM trial.VIEWRLSPROS

/*OTORGO PERMISOS AL ROL*/
GRANT SELECT ON [trial].[VIEWRLSPROS] TO [BBM_PROFESIONALES]
GO




	PRINT USER
	EXECUTE AS USER = 'LOGOPEDA'
	PRINT USER
	--LOGOPEDA

	SELECT * FROM trial.VIEWRLSPROS

	REVERT

	PRINT USER


									 

/*CREAMOS UNA FUNCIÓN QUE BUSQUE EN SYSNAME Y ME DEVUELVA EL NOMBRE DE USUARIO*/
DROP Function IF Exists trial.fn_BBMRLS
GO
CREATE OR ALTER FUNCTION trial.fn_BBMRLS (@FILTERCOL sysname) --> busca en sysname
RETURNS TABLE
WITH SCHEMABINDING
AS
RETURN SELECT 1 as fn_BBMELSECUREDATA
-- filter out records based on database user name 
where @FILTERCOL = user_name(); --> Devuelve el usuario conectado
GO


/*CREAMOS POLITICA DE SEGURIDAD DE PROFESIONALES*/
DROP SECURITY POLICY IF EXISTS trial.BBMFILTROASIGNACIONESPROS
GO
CREATE SECURITY POLICY trial.BBMFILTROASIGNACIONESPROS
ADD FILTER PREDICATE trial.fn_BBMRLS(Pro_asignado) --> add filter predicate + schema.nombre_funcion + (campo que toma como parametro)
ON trial.VIEWRLSPROS --> Sobre la tabla
WITH (STATE = ON); --> Con la política activada para que comience a funcionar y
GO
/*DDB -> SECURITY -> SECURITY POLICIES*/




/*HAGO UNA PRUEBA CON UN PROFESIONAL*/
-- PRIMERO PROFESIONALES	
PRINT USER

EXECUTE AS USER = 'LOGOPEDA'

PRINT USER
--LOGOPEDA

SELECT * FROM trial.VIEWRLSPROS

REVERT

PRINT USER
--dbo


/*HAGO UNA RÉPLICA CON LOS AUXILIARES*/


	-- =============================================
-- Create View template
-- =============================================
USE BBM_ASPACE
GO

DROP VIEW IF EXISTS trial.VIEWRLSAUX
GO

CREATE VIEW trial.VIEWRLSAUX WITH SCHEMABINDING AS
SELECT        Usuario, Nombre_Usuario, Aux_asignado
FROM            trial.BBM_USERDATASSIGNEDAUX
go

PRINT USER
SELECT * FROM trial.VIEWRLSAUX

/*OTORGO PERMISOS AL ROL*/
GRANT SELECT ON [trial].[VIEWRLSAUX] TO [BBM_AUXILIARES]
GO




	PRINT USER
	EXECUTE AS USER = 'AUX04'
	PRINT USER
--AUX04

	SELECT * FROM trial.VIEWRLSAUX

	REVERT

	PRINT USER


									 

/*CREAMOS UNA FUNCIÓN QUE BUSQUE EN SYSNAME Y ME DEVUELVA EL NOMBRE DE USUARIO*/
DROP Function IF Exists trial.fn_BBMRLSAUX
GO
CREATE OR ALTER FUNCTION trial.fn_BBMRLSAUX (@FILTERCOL sysname) --> busca en sysname
RETURNS TABLE
WITH SCHEMABINDING
AS
RETURN SELECT 1 as fn_BBMELSECUREDATA
-- filter out records based on database user name 
where @FILTERCOL = user_name(); --> Devuelve el usuario conectado
GO


/*CREAMOS POLITICA DE SEGURIDAD DE AUXILIAR*/
DROP SECURITY POLICY IF EXISTS trial.BBMFILTROASIGNACIONESAUX

CREATE SECURITY POLICY trial.BBMFILTROASIGNACIONESAUX
ADD FILTER PREDICATE trial.fn_BBMRLSAUX(Aux_asignado) --> add filter predicate + schema.nombre_funcion + (campo que toma como parametro)
ON trial.VIEWRLSAUX --> Sobre la tabla
WITH (STATE = ON); --> Con la política activada para que comience a funcionar y
GO
/*DDB -> SECURITY -> SECURITY POLICIES*/




/*HAGO UNA PRUEBA CON UN AUXILIAR*/
-- PRIMERO AUXILIAR	
PRINT USER

EXECUTE AS USER = 'AUX04'

PRINT USER
--AUX04


SELECT * FROM trial.VIEWRLSAUX

REVERT

PRINT USER
--dbo



/*PROBAMOS CON INSERTAR*/
/*PARA DARLE VERACIDAD VAMOS A DAR PERMISOS DE ACTUALIZACIÓN SOLAMENTE SOBRE UNA TABLA, Y A UN NUEVO USUARIO ADMINISTRATIVO, QUE ES EL QUE ASIGNA LOS PACIENTES*/

--CREO EL USUARIO
CREATE USER ASIGNADOR WITHOUT LOGIN; 



-- Granting UPDATE and INSERT access A LOS PROS
GRANT SELECT ON [trial].[BBM_USERDATASSIGNEDPROS] TO [ASIGNADOR]
GO
GRANT UPDATE, INSERT ON trial.BBM_USERDATASSIGNEDPROS TO ASIGNADOR;
GO


/*CON UN TRIGGER, HACEMOS QUE LOS DATOS QUE SE INSERTAN EN LA TABLA DE PROFESIONALES, SE REPLICAN EN LA DE AUXILIARES*/
DROP TRIGGER IF EXISTS trial.trg_UPDATEANOTHERTABLE
GO

CREATE OR ALTER TRIGGER trial.trg_UPDATEANOTHERTABLE ON [trial].[BBM_USERDATASSIGNEDPROS] 
  AFTER UPDATE,INSERT
AS 
BEGIN
   --SET NOCOUNT ON agregado para evitar conjuntos de resultados adicionales
   -- interferir con las instrucciones SELECT.
  SET NOCOUNT ON;

  -- OBTENER LOS VALORES DE LOS CAMPOS
	DECLARE @R int, @U VARCHAR(20), @NU VARCHAR(10), @PA VARCHAR(30), @AA VARCHAR(30)
		SELECT @R = new.ROW#			FROM inserted new;
		SELECT @U =  new.Usuario		FROM inserted new;
		SELECT @NU = new.Nombre_Usuario FROM inserted new;
		SELECT @PA = new.Pro_asignado	FROM inserted new;
		SELECT @AA = new.Aux_asignado	FROM inserted new;

  /*ACTUALIZAR PROS -> ACTUALIZA AUX*/
	 IF (UPDATE(Usuario) OR UPDATE(Nombre_Usuario) OR UPDATE(Pro_asignado)OR UPDATE(Aux_asignado))  /*COGE ESTOS DATOS DE LA TABLA TEST*/
        BEGIN
			INSERT INTO trial.BBM_USERDATASSIGNEDAUX (Usuario, Nombre_Usuario, Pro_asignado, Aux_asignado) VALUES (@U, @NU, @PA,@AA);
			DELETE FROM trial.BBM_USERDATASSIGNEDAUX WHERE ROW# = @R;
            PRINT 'THE EMPLOYEE HAS BEEN UPDATED/INSERTED SUCCESSFULLY'
        END
 END




/*DEMOSTRAMOS EL FUNCIONAMIENTO*/

PRINT USER
GO
-- dbo

SELECT * FROM trial.BBM_USERDATASSIGNEDPROS
GO


-- UPDATE USUARIO QUE SE ASIGNA
EXECUTE AS USER = 'ASIGNADOR';
GO
PRINT USER

SELECT * FROM trial.BBM_USERDATASSIGNEDPROS
WHERE Nombre_Usuario = 'Brigida'
GO



/*PROBAMOS A ACTUALIZAR UNA FILA, PORQUE HA CAMBIADO UN PACIENTE DE AUXILIAR*/
UPDATE trial.BBM_USERDATASSIGNEDPROS 
SET Aux_asignado = 'AUX04' 
WHERE Nombre_Usuario = 'Brigida'
GO
-- (1 row affected)



REVERT
PRINT USER



EXECUTE AS USER = 'AUX04';

PRINT USER
--AUX04

/*TRATAMOS DE VER LA ACTUALIZACIÓN EN LA TABLA DE AUXILIARES PARA VER QUE EL TRIGGER SE DISPARA*/

SELECT * FROM trial.VIEWRLSAUX
GO

REVERT

PRINT USER
--dbo




/*BLOCK PREDICATES*/

/*PARA ESTA PRUEBA, A MÍ ME INTERESA QUE SOBRE LA TABLA AUXILIARES NADIE ACTUALICE NADA, Y TAN SOLO LA ACTUALIZACIÓN LA HAGA EL TRIGGER*/

ALTER SECURITY POLICY trial.BBMFILTROASIGNACIONESAUX
ADD BLOCK PREDICATE trial.fn_BBMRLSAUX (Aux_asignado)
ON trial.BBM_USERDATASSIGNEDAUX AFTER UPDATE, 
ADD BLOCK PREDICATE trial.fn_BBMRLSAUX(Aux_asignado)
ON trial.BBM_USERDATASSIGNEDAUX AFTER INSERT;
GO 
/*CON ESTO NO SE DEBERÍA DE PODER HACER NADA EN ESA TABLA EN CUANTO A INSERCIONES */

/*DEMOSTRAMOS EL FUNCIONAMIENTO*/

PRINT USER
GO
-- dbo

SELECT * FROM trial.BBM_USERDATASSIGNEDAUX
GO


-- Granting UPDATE and INSERT access A LOS AUX
GRANT SELECT ON [trial].[BBM_USERDATASSIGNEDAUX] TO [ASIGNADOR]
GO
GRANT UPDATE, INSERT ON trial.BBM_USERDATASSIGNEDAUX TO ASIGNADOR;
GO



-- UPDATE USUARIO QUE SE ASIGNA
EXECUTE AS USER = 'ASIGNADOR';
GO
PRINT USER

SELECT * FROM trial.BBM_USERDATASSIGNEDAUX
GO



/*PROBAMOS A ACTUALIZAR UNA FILA, PORQUE HA CAMBIADO UN PACIENTE DE AUXILIAR*/
UPDATE trial.BBM_USERDATASSIGNEDAUX 
SET Aux_asignado = 'AUX05' 
WHERE Nombre_Usuario = 'Brigida';
GO
-- (1 row affected)



REVERT
PRINT USER


/*TRATAMOS DE VER LA ACTUALIZACIÓN EN LA TABLA DE AUXILIARES PARA VER QUE NO HAY ACTUALIZACIÓN*/


SELECT * FROM trial.BBM_USERDATASSIGNEDAUX
WHERE Aux_asignado = 'AUX05'
GO



/*INSERTAMOS EN LA TABLA PROS Y VEMOS LOS EFECTOS*/



EXECUTE AS USER = 'ASIGNADOR';
GO
PRINT USER

SELECT * FROM trial.BBM_USERDATASSIGNEDAUX
WHERE Aux_asignado = 'AUX05'
GO



/*PROBAMOS A INSERTAR UNA FILA FICTICIA*/
INSERT INTO trial.BBM_USERDATASSIGNEDPROS VALUES ('TEST','DEMOSTRAR','INSERT','TRIGGER')
GO
-- (1 row affected)

--VEMOS QUE FALLA TAMBIÉN EL TRIGGER




REVERT
PRINT USER

