DROP DATABASE IF EXISTS BBM_ASPACE;
CREATE DATABASE BBM_ASPACE CHARSET utf8mb4;
USE BBM_ASPACE;

CREATE TABLE BBM_Usuario (
  Usuario_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_1 VARCHAR(100) NOT NULL,
  Nombre_2 VARCHAR(100) NOT NULL,
  Apellido_1 VARCHAR(100) NOT NULL,
  Apellido_2 VARCHAR(100) NOT NULL,
  DNI VARCHAR(100) NOT NULL,
  Otros_Detalles VARCHAR(100) NOT NULL
);


INSERT INTO BBM_Usuario VALUES('1', 'NOMBRETEST','NOMBRE2', 'APELLIDO1','APELLIDO2','123456789','LOREM');

                                
