Drop database if exists BBM_ASPACE;

create database BBM_ASPACE;

CREATE TABLE BBM_USERDATASSIGNEDPROS(
	Usuario varchar (20) NOT NULL,
	Nombre_Usuario varchar(10) NULL,
	Pro_asignado Varchar(30) NULL,
    Aux_asignado varchar(30));



INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER01','Pepe','PSICOLOGO','AUX01');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER02','Paco','LOGOPEDA','AUX02');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER03','Lola','ASISTENTE_SOCIAL','AUX03');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER04','Diana','TERAPEUTA_OCUPACIONAL','AUX04');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER05','Jose','FISIOTERAPEUTA','AUX05');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER06','Luis','PSICOLOGO','AUX05');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER07','Julia','LOGOPEDA','AUX04');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER08','Cristina','ASISTENTE_SOCIAL','AUX03');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER08','Toribio','TERAPEUTA_OCUPACIONAL','AUX02');
INSERT INTO BBM_USERDATASSIGNEDPROS VALUES ('USER00','Brigida','FISIOTERAPEUTA','AUX01');